#!/bin/bash
for component in components/*; do
	echo $component
	npm exec -w $component -- origami-build-tools verify && 
	npm exec -w $component -- origami-build-tools test && 
	sleep 10 &&
	echo
done
