name: Percy components/o-table
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
     - "components/o-table/package.json"
     - "components/o-table/package-lock.json"
     - "components/o-table/origami.json"
     - "components/o-table/main.js"
     - "components/o-table/main.scss"
     - "components/o-table/demos/**"
     - "components/o-table/src/**"
  push:
    branches: main
    paths:
     - "components/o-table/package.json"
     - "components/o-table/package-lock.json"
     - "components/o-table/origami.json"
     - "components/o-table/main.js"
     - "components/o-table/main.scss"
     - "components/o-table/demos/**"
     - "components/o-table/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
        registry-url: 'https://origami-npm-registry-prototype.herokuapp.com'
    - run: npm ci
