on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
          command: manifest
          monorepo-tags: true
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://origami-npm-registry-prototype.herokuapp.com'
        if: ${{ steps.release.outputs.releases_created }}
      - run: echo ${{join(steps.release.outputs.*, '\n')}}
      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm publish -ws
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created }}
