name: test components/o-errors
concurrency:
  group: $
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx npm exec -w components/o-errors -- origami-build-tools verify
    - run: npx npm exec -w components/o-errors -- origami-build-tools test
